name: Docker CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -t logger .
    - name: Run container
      run: |
        mkdir -p logs
        echo -e "test1\nhello docker" | docker run -i -v "$(pwd)/logs:/home/logs" logger
    - name: Check log file
      run: |
        cat logs/log.txt
        grep "test1" logs/log.txt
        grep "hello docker" logs/log.txt
